config/routes.rb
Rails.application.routes.draw do
  resources :polls
  root 'polls#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
    class Poll < ApplicationRecord
        after_commit :notify_pusher, on: [:create, :update]
        def notify_pusher
        Pusher.trigger('poll', 'new', self.as_json)
        end  
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
    @poll = Poll.new
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :laptop)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PusherRailsChart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/polls/_form.html.erb
 <%= form_with(model: poll, remote: true, format: :json, id: 'add_poll') do |form| %>
      <% if poll.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>
          <ul>
          <% poll.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :poll_name, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label :laptop, "Do you own a laptop? " %><br />
        <%= form.label :laptop, "Yes", :value => "true" %>
        <%= form.radio_button :laptop, 'yes', :checked => true %>
        <%= form.label :laptop, "No", :value => "false" %>
        <%= form.radio_button :laptop, 'no'%>
      </div>
      <div class="actions">
        <%= form.submit 'submit', class: "btn btn-success"%>
      </div>
    <% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-5 offset-1">
          <p id="notice"><%= notice %></p>
          <h1>Polls</h1>
          <table id='poll-table' class="table table-hover">
            <thead class="thead-light">
              <tr>
                <th>Name</th>
                <th>Laptop</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @polls.each do |poll| %>
                <tr>
                  <td><%= poll.name %></td>
                  <td><%= poll.laptop %></td>
                  <td><%= link_to 'Show', poll %></td>
                  <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
                  <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="col-6">
          <%= pie_chart [["Yes", Poll.where(laptop: "yes").count], ["No", Poll.where(laptop: "no").count]], id:'polls'%> 
        </div>
      </div>

       <div class="row">
        <div class='col-11 offset-1 col-sm-4'>
          <h3>New poll</h3>
          <%= render 'form', poll: @poll %>
        </div>
      </div>
    </div>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poll.name %>
</p>

<p>
  <strong>Laptop:</strong>
  <%= @poll.laptop %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>